#!/usr/bin/env bash

find . \( -iname "*.elf" -or -iname "*.hex" -or \
          -iname "*.a"   -or -iname "*.lst" -or \
          -iname "*.dll" -or -iname "*.o"   -or \
          -iname "*.so"  -or -iname "*.bin" -or \
          -iname "*.srec" \) -delete
